services:
  db: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    ports:
      - "3306:3306"

  node:
    build:
      context: node
    container_name: node
    networks:
      - node-network
    # volumes:
    #   - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  nginx:
    restart: always
    build: 
      context: nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:8080"

networks:
  node-network: